ibisml/steps/common.py
ibisml/transforms/common.py

After the https://github.com/ibis-project/ibis/pull/7277 PR, the existing deferred imports do not seem to work. I have updated these imports to adjust. 
After making these changes, it seems to be working again.

fix: update Deferred import

---

ibisml/transforms/encode.py
pyproject.toml
tests/test_core.py

This PR aims to make it easier to install the extra for dask[dataframe], adds a docstring for `OneHotEncode` used with a `Recipe`, and improves testing coverage for [core.py](https://github.com/ibis-project/ibisml/blob/main/ibisml/core.py). 
Similar docstrings could be added for the other classes and to include docstrings for functions, but I wanted to ensure this was the type of style we wanted to go for. Happy to make any changes!

Minor Fixes: Dask Extra, OneHotEncode example, categorize_pandas tests

---

ibisml/steps/__init__.py
ibisml/steps/standardize.py
ibisml/transforms/__init__.py
ibisml/transforms/standardize.py
tests/test_standardize.py

Hi team!
I thought this is a very interesting project and want to contribute in some way, so I implemented the MinMaxScaler functionality.
Should I also implement a base class for Scaler?
Please let me know if there is anything I am missing in the steps for contribution!

feat: Add MinMaxScaler.

---

docs/_quarto.yml
ibisml/steps/__init__.py
ibisml/steps/temporal.py
ibisml/transforms/__init__.py
ibisml/transforms/temporal.py
tests/test_temporal.py

Closes #14, this is a recreation of #15, which I will close tomorrow. 
The test has been updated as well. This is how I have been using it to try this out, similar to the previous PR. 
```
from ibis.interactive import *
import ibisml as ml
con = ibis.duckdb.connect()
t = con.sql("select get_current_timestamp() AS datetime")
step = ml.ExpandDateTime("datetime")
transform = step.fit(t, ml.core.Metadata())
res = transform.transform(t)
res
```
When no literal values are passed to the components on the return, all columns except second and millisecond are chosen.

feat: ExpandDateTime convenience (datetime components)

---

ibisml/core.py
tests/test_core.py

This better matches the other `to_*` method conventions.

Rename `to_table` to `to_ibis`

---

ibisml/select.py
ibisml/steps/__init__.py
ibisml/steps/encode.py
tests/test_encode.py

Required for https://nvidia-merlin.github.io/NVTabular/v1.0.0/examples/winning-solution-recsys2020-twitter/01-02-04-Download-Convert-ETL-with-NVTabular-Training-with-XGBoost.html.
Based on https://github.com/rapidsai/deeplearning/blob/main/RecSys2020Tutorial/03_4_CountEncoding.ipynb.
I don't treat nulls as a meaningful unknown value; to get counts for nulls, add a step like `FillNA("UNKNOWN")` first.

feat(steps): implement a step to count encode cols

---

ibisml/core.py
ibisml/select.py
ibisml/steps/encode.py
tests/test_core.py
tests/test_select.py

Previously all steps would only rely on `X` during fitting, so we completely ignored `y` if it was passed in. We now have at least one desired `Step` that relies on `y` during the fitting process, which means we need to start properly handling `y` in `fit`/`fit_transform`.
This PR handles:
- normalizing `X` and `y` to a single `Table` from a variety of possible inputs
- Plumbing through `X` and `y` metadata through `fit` and `fit_transform`.
~Still needs a bunch of tests, but I believe this works already in general.~

Plumb through `y` in `fit` and `fit_transform`

---

ibisml/steps/__init__.py
ibisml/steps/feature_selection.py
tests/test_feature_selection.py

Add zero variance filter:
1. remove numeric features with 0 variance 
- used a tolerance level for considering variance as zero. Columns with variance less than this tolerance will be removed. 
Default is 1e-4. 
3. remove non-numeric columns with only 1 constant value
- `NULL` value is not counted in the `nunique()`
**Issues**
https://github.com/ibis-project/ibisml/issues/42

feat(steps): implement zero-variance filter

---

ibisml/steps/__init__.py
ibisml/steps/feature_engineering.py
tests/test_feature_engineering.py

Add polynomial features
Resolve #41

feat(steps): add transform for polynomial features

---

ibisml/steps/encode.py
tests/test_encode.py

This PR added the following
- use `ifelse` to avoid casting Boolean to Int
- Handle issues in #54 
- Added unit test for one hot encoding
```python
>>> import ibis
>>> import ibisml as ml
>>> import pandas as pd
>>>
>>> t_train = ibis.memtable(
...         {
...             "time": [
...                 pd.Timestamp("2016-05-25 13:30:00.023"),
...                 pd.Timestamp("2016-05-25 13:30:00.023"),
...                 pd.Timestamp("2016-05-25 13:30:00.030"),
...                 pd.Timestamp("2016-05-25 13:30:00.041"),
...                 pd.Timestamp("2016-05-25 13:30:00.048"),
...                 pd.Timestamp("2016-05-25 13:30:00.049"),
...                 pd.Timestamp("2016-05-25 13:30:00.072"),
...                 pd.Timestamp("2016-05-25 13:30:00.075"),
...             ],
... …
```

fix(steps): avoid bool-to-int cast and handle NULL

---

docs/_quarto.yml
ibisml/steps/discretize.py
ibisml/steps/feature_engineering.py

add newly added steps to website

docs: add new steps to website

---

.github/workflows/publish.yml

The TestPyPI publishing step fails right now, because the version already exists.
Chose to create a post-release (instead of a development release), since it will be installable without any additional flags (`--pre`). While it's not recommended to modify code in post-releases, this is only for TestPyPI publishing (i.e. nobody should be consuming it, anyway).

ci: add a unique identifier to publish to TestPyPI

---

.github/workflows/docs.yml

Dask had an issue of this ```TypeError: descriptor '__call__' for 'type' objects doesn't apply to a 'property' object``` for lower version.  The support of dask is not calculated because the dask error. 
I update dask to its latest version, it solves the problem. 
Check with https://github.com/dask/dask/pull/11035 for details.
Rendered webpage:  https://jitingxu1.github.io/ibis-ml/support_matrix.html

fix(docs): fix dask in support matrix

---

docs/tutorial/_tool-chooser.md

"scikit-learn" rendered across two lines, elongating the box and causing inconsistency:

docs(website): shorten "scikit-learn" to "sklearn"

---

docs/_quarto.yml
docs/tutorial/How_to_create_your_own_transformer.qmd

add custom transformation to website
It is part of #69 and #92

docs(website): add custom transformation to website

---

docs/theme-dark.scss
docs/theme-light.scss

TL;DR the tool chooser CSS is predicated on `1rem` padding, not `2rem`
We need to overwrite this: https://github.com/quarto-dev/quarto-cli/blob/v1.5.52/src/resources/formats/html/bootstrap/themes/flatly.scss#L68
See the problem:
It's correct on the Quarto website:
Now it looks good:
Also in dark mode:

fix(website): restore padding to Bootstrap default

---

docs/_quarto.yml
ibis_ml/__init__.py
ibis_ml/utils/_train_test_split.py
tests/test_train_test_split.py

add train test split based on the functions in the [tutorial](https://ibis-project.github.io/ibis-ml/tutorial/pytorch.html).
Not sure if this is the right module for this utility function, I am open to all kids of recommendation.
Another Reference: https://engineeringfordatascience.com/posts/ml_repeatable_splitting_using_hashing/

feat(utils): provide a `train_test_split` function

---

docs/_quarto.yml
ibis_ml/__init__.py
ibis_ml/utils/_split.py

When I went to visit the website, I saw a train-test split section with a train-test split function; it makes sense for the section to be a bit more generalized, both to perhaps include things like CV in the future, should we add it, and to just be less redundant.

docs(website): generalize name to "Data splitting"

---

ibis_ml/steps/_temporal.py

docs(steps): fix wrong name for timestamp selector

---

ibis_ml/utils/_split.py

fix(utils): fix possible name collision in `train_test_split`

---

ibis_ml/core.py
ibis_ml/steps/_common.py
tests/test_common.py
tests/test_core.py

For example, from the example notebook:
```python
import ibis_ml as ml
flights_rec = ml.Recipe(
ml.ExpandDate("date", components=["dow", "month"]),
ml.Drop("date"),
ml.TargetEncode(ml.nominal()),
ml.DropZeroVariance(ml.everything()),
ml.MutateAt("dep_time", ibis._.hour() * 60 + ibis._.minute()),
ml.MutateAt(ml.timestamp(), ibis._.epoch_seconds()),
ml.Cast(ml.numeric(), "float32"),
)
flights_rec.get_params()
```
will yield:
```python
{'steps': (ExpandDate(cols(('date',)), components=['dow', 'month']),
Drop(cols(('date',))),
TargetEncode(nominal(), smooth=0.0),
DropZeroVariance(everything(), tolerance=0.0001),
MutateAt(cols(('dep_time',)), ((_.hour() * 60) + _.minute())),
MutateAt(timestamp(), _.epoch_seconds()),
Cast(numeric(), 'float32')),
'expanddate': ExpandDate(cols(('date',)), …
```

feat(core): implement `get_params()` API for steps

---

docs/_quarto.yml
docs/reference/support-matrix/step_config.yml
ibis_ml/steps/__init__.py
ibis_ml/steps/_temporal.py
tests/test_core.py
tests/test_temporal.py

refactor(steps): rename class to `ExpandTimestamp`

---

pyproject.toml

The polars integration wasn't being tested since it wasn't installed on CI.

chore: add polars to the dev dependencies

---

ibis_ml/core.py
tests/test_common.py
tests/test_core.py

Related to #135 and #136 
Before this PR, it wasn't possible to call `set_params()` on `Step` objects, and `Recipe.set_params()` only trivially set the `steps` param. With this PR, you can actually set the parameters listed by `Recipe.get_params()` (and `Step.get_params()`), which is more robust and akin to scikit-learn.

feat(core): implement a more robust `set_params()`

---

docs/tutorial/pytorch.qmd
docs/tutorial/scikit-learn.qmd
docs/tutorial/xgboost.qmd

`dropna` -> `drop_null`
use `.filter()` instead of the brackets thing

docs: fix warnings from deprecations

---

ibis_ml/steps/_impute.py
tests/test_impute.py

changes:
1. add unit test for _impute.py
2. raise a value error if one column is all NULL, because it does not fulfill users' original goal.
resolve #117

fix(steps): add unit test and fix null cols for impute
